### ISSUE TITLE
Can not convert

### ISSUE THREAD

**Issue by semantic-tester** [edwardyehuang/CAR#2]
I am trying the code while stopped at step 2. I can not convert downloaded dataset. the final error is related to os.fspath. I am wondering there might be something wrong about the output path part. What should inside the {   }? Can you give an example for it?

**Comment by edwardyehuang** [comment]
> I am trying the code while stopped at step 2. I can not convert downloaded dataset. the final error is related to os.fspath. I am wondering there might be something wrong about the output path part. What should inside the { }? Can you give an example for it?

Hi! Could you provide your config file and error output?

**Comment by semantic-tester** [comment]
Thank you for reply.
I am using Ubuntu 22. I put the codes under /home/xuanwu/Downloads/CAR. I am not using any config file. And the downloaded unziped directory is just under CAR as pascalcontext. 
this is the command:
python3 ids/tools/convert_record.py \
--convert_datasets=pascalcontext \
--tfrecord_outputs=/home/xuanwu/Downloads/CAR/pascalcontext

But I got this:
Traceback (most recent call last):
  File "/home/xuanwu/Downloads/CAR/ids/tools/convert_record.py", line 55, in <module>
    app.run(main)
  File "/home/xuanwu/.local/lib/python3.10/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/xuanwu/.local/lib/python3.10/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/xuanwu/Downloads/CAR/ids/tools/convert_record.py", line 51, in main
    dataset.save_tf_record(output_dir, compress=FLAGS.compress, size_split=FLAGS.size_split)
  File "/home/xuanwu/Downloads/CAR/ids/dataset.py", line 100, in save_tf_record
    train_ds, val_ds = self.load_trainval_tensor_ds()
  File "/home/xuanwu/Downloads/CAR/ids/dataset.py", line 156, in load_trainval_tensor_ds
    training_paths, val_paths = self.load_data_paths(self.__dataset_dir)
  File "/home/xuanwu/Downloads/CAR/ids/pascal_context.py", line 41, in load_data_paths
    image_dir = os.path.join(dataset_dir, INAGE_DIR)
  File "/usr/lib/python3.10/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

I guess that is some path input error. However, I have tried many different input and it still failed.

**Comment by edwardyehuang** [comment]
Hi! You may add "--pascalcontext_path={downloaded raw dataset dir}" flags

**Comment by edwardyehuang** [comment]
I just fixed the documentation at https://github.com/edwardyehuang/CAR/blob/master/docs/perpare_dataset.md.

Sorry for any inconvenience caused

**Comment by semantic-tester** [comment]
Thank you. That solves the problem
